stages:
  - test
  - build
  - deploy


####################################################################################################
include:

  - component: $CICD_COMPONENTS_PROJECT/test_build_vite@$CICD_COMPONENTS_COMMIT_REF
    inputs:
      stage: test
    rules:
      - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
        when: never
      - if: $CI_COMMIT_BRANCH == 'production'
        when: never
      - when: always

  - component: $CICD_COMPONENTS_PROJECT/build_vite@$CICD_COMPONENTS_COMMIT_REF
    inputs:
      stage: build
    rules:
      - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
        when: always
      - if: $CI_COMMIT_BRANCH == 'production'
        when: always
      - when: never
  
  - component: $CICD_COMPONENTS_PROJECT/deploy_to_static_webserver@$CICD_COMPONENTS_COMMIT_REF
    inputs:
      folder_name: groups_dashboards
      environment: staging
    rules:
      - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
        when: always
      - when: never

  - component: $CICD_COMPONENTS_PROJECT/deploy_to_static_webserver@$CICD_COMPONENTS_COMMIT_REF
    inputs:
      folder_name: groups_dashboards
      environment: production
    rules:
      - if: $CI_COMMIT_BRANCH == 'production'
        when: always
      - when: never

