stages:
  - test
  - build
  - package
  - deploy

####################################################################################################
include:

  - component: gitlab.fht.org/computational-biology-sw-web-dev-unit/cicd-components/lint_dockerfile@initial_setup
    inputs:
      stage: test
    rules:
      - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
        when: never
      - if: $CI_COMMIT_BRANCH == 'production'
        when: never
      - when: always

  - component: gitlab.fht.org/computational-biology-sw-web-dev-unit/cicd-components/test_build_vite@initial_setup
    inputs:
      stage: test
    rules:
      - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
        when: never
      - if: $CI_COMMIT_BRANCH == 'production'
        when: never
      - when: always

  - component: gitlab.fht.org/computational-biology-sw-web-dev-unit/cicd-components/build_vite@initial_setup
    inputs:
      stage: build
    rules:
      - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
        when: always
      - if: $CI_COMMIT_BRANCH == 'production'
        when: always
      - when: never

  - component: gitlab.fht.org/computational-biology-sw-web-dev-unit/cicd-components/package_image@initial_setup
    rules:
      - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
        when: always
      - when: never

  - component: gitlab.fht.org/computational-biology-sw-web-dev-unit/cicd-components/deploy_to_environment@initial_setup
    rules:
      - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
        when: always
      - when: never

  - component: gitlab.fht.org/computational-biology-sw-web-dev-unit/cicd-components/package_image@initial_setup
    inputs:
      tag: $CI_COMMIT_SHORT_SHA
    rules:
      - if: $CI_COMMIT_BRANCH == 'production'
        when: always
      - when: never

  - component: gitlab.fht.org/computational-biology-sw-web-dev-unit/cicd-components/deploy_to_environment@initial_setup
    inputs:
      tag: $CI_COMMIT_SHORT_SHA
      environment: production
    rules:
      - if: $CI_COMMIT_BRANCH == 'production'
        when: always
      - when: never
